language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pip install sphinx
  - pytest --cov flask_filter
  - bash ./publish.sh
env:
  global:
  - GH_USER: exleym
  - GH_REPO: Flask-Filter
  - GH_TOKEN: $GITHUB_TOKEN
after_success:
  - coveralls
